modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "hotbarredirect"
version = "1.20.1"
displayName = "HotbarRedirect"
authors = "kazhi"
description = '''Reload and redirect hotbar file in minecraft'''

[[dependencies.hotbarredirect]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hotbarredirect]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.22)"
ordering = "NONE"
side = "BOTH"
